### ISSUE TITLE
Small mistake (I think)

### ISSUE THREAD

**Issue by Somnef** [ASSAZZIN-01/UmojaHack-Africa-2022#1]
Hey Assazzin, thank you for sharing your work, it's really clean and insightful. I just wanted to point out what I think is a small typo. I think that you forgot a minus ( - ) sign in the last shift of your process class, ending up with two identical columns!
Again, thank you very much for your very nice work, and I hope that my observation is on point. Keep up the nice work!
![image](https://user-images.githubusercontent.com/53086941/159377472-7d403f77-de74-495a-a40d-27a67a473f71.png)

**Comment by ASSAZZIN-01** [comment]
thanks for pointing out this small typo mistake !
